version: "3"

services:
  gopoliceinterview:
    container_name: gopoliceinterview
    image: gopoliceinterview
    restart: unless-stopped
    environment:
      - "TIMEOUT=10"
    volumes:
      - "./config.json:/config.json"
